---
development:
  cloud_name: dsgd2hpbg
  api_key: '585892794352456'
  api_secret: uciEcBP1ruy3xp592AUPw56l2-A
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dsgd2hpbg
  api_key: '585892794352456'
  api_secret: uciEcBP1ruy3xp592AUPw56l2-A
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dsgd2hpbg
  api_key: '585892794352456'
  api_secret: uciEcBP1ruy3xp592AUPw56l2-A
  enhance_image_tag: true
  static_image_support: false
